import { Platform, StyleSheet } from 'react-native';
import { ADMIN_COLORS } from './constants';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ADMIN_COLORS.bg,
  },
  shell: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: ADMIN_COLORS.bg,
  },
  shellCompact: {
    flexDirection: 'column',
  },
  sidebar: {
    width: 250,
    backgroundColor: ADMIN_COLORS.sidebar,
    borderRightWidth: 1,
    borderRightColor: ADMIN_COLORS.sidebarBorder,
  },
  sidebarCompact: {
    width: '100%',
    maxHeight: 320,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: ADMIN_COLORS.sidebarBorder,
  },
  sidebarHeader: {
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: ADMIN_COLORS.sidebarBorder,
  },
  sidebarBrand: {
    color: ADMIN_COLORS.accent,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -1,
  },
  sidebarMeta: {
    marginTop: 4,
    color: ADMIN_COLORS.textMuted,
    fontSize: 12,
  },
  sidebarScrollContent: {
    paddingHorizontal: 10,
    paddingVertical: 14,
  },
  sidebarSection: {
    marginBottom: 16,
  },
  sidebarSectionTitle: {
    color: ADMIN_COLORS.textDim,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    paddingHorizontal: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  navItem: {
    minHeight: 38,
    borderRadius: 8,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 2,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : null),
  },
  navItemHover: {
    backgroundColor: '#262b34',
  },
  navItemPressed: {
    opacity: 0.92,
  },
  navItemActive: {
    backgroundColor: '#2a2e35',
  },
  navItemText: {
    color: '#cfd5e1',
    fontSize: 13,
    fontWeight: '500',
    flexShrink: 1,
  },
  navItemTextHover: {
    color: '#edf0f8',
  },
  navItemTextActive: {
    color: ADMIN_COLORS.text,
    fontWeight: '700',
  },
  main: {
    flex: 1,
  },
  topBar: {
    minHeight: 58,
    backgroundColor: ADMIN_COLORS.topBar,
    borderBottomWidth: 1,
    borderBottomColor: '#31111f',
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  windowDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#c5c8d0',
  },
  topBrand: {
    color: ADMIN_COLORS.accent,
    fontSize: 18,
    fontWeight: '800',
  },
  adminPill: {
    backgroundColor: '#7e3157',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  adminPillText: {
    color: '#f6ddec',
    fontSize: 11,
    fontWeight: '700',
  },
  topBarActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f232b',
    borderWidth: 1,
    borderColor: '#2c313a',
  },
  contentScroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 18,
  },
  contentMobile: {
    paddingHorizontal: 12,
  },
  hero: {
    backgroundColor: ADMIN_COLORS.accentSoft,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: ADMIN_COLORS.accentBorder,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  heroTitle: {
    color: ADMIN_COLORS.text,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  heroSubtitle: {
    marginTop: 4,
    color: '#9f90a0',
    fontSize: 14,
  },
  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  metricPanel: {
    minWidth: 220,
    flexGrow: 1,
    backgroundColor: ADMIN_COLORS.surface,
    borderWidth: 1,
    borderColor: ADMIN_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  metricIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    color: ADMIN_COLORS.text,
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 36,
  },
  metricLabel: {
    marginTop: 2,
    color: ADMIN_COLORS.textMuted,
    fontSize: 14,
  },
  metricHint: {
    marginTop: 4,
    color: ADMIN_COLORS.textDim,
    fontSize: 12,
  },
  searchPanel: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#432033',
    backgroundColor: ADMIN_COLORS.searchBg,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchPlaceholder: {
    color: '#746476',
    fontSize: 14,
  },
  panel: {
    backgroundColor: ADMIN_COLORS.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: ADMIN_COLORS.border,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  panelTitle: {
    color: ADMIN_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  panelMeta: {
    marginTop: 4,
    color: ADMIN_COLORS.textMuted,
    fontSize: 13,
  },
  table: {
    minWidth: 880,
    marginTop: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#2a303b',
    paddingBottom: 14,
  },
  headerCell: {
    color: ADMIN_COLORS.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#242a34',
    minHeight: 56,
  },
  tableCell: {
    justifyContent: 'center',
    paddingVertical: 14,
    paddingRight: 12,
  },
  customerCellWide: {
    width: 240,
  },
  businessCell: {
    width: 300,
  },
  contactCell: {
    width: 170,
  },
  emailCell: {
    width: 320,
  },
  nameCell: {
    width: 160,
  },
  smallCell: {
    width: 140,
  },
  actionCell: {
    width: 130,
  },
  iconCell: {
    width: 50,
    alignItems: 'flex-end',
  },
  customerInfoCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inlineIconCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  cellPrimary: {
    color: ADMIN_COLORS.text,
    fontSize: 13,
    fontWeight: '700',
  },
  cellSecondary: {
    marginTop: 3,
    color: ADMIN_COLORS.textMuted,
    fontSize: 13,
  },
  cellMutedItalic: {
    color: ADMIN_COLORS.textDim,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  neutralBadge: {
    alignSelf: 'flex-start',
    backgroundColor: ADMIN_COLORS.badge,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  neutralBadgeText: {
    color: ADMIN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  typeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: ADMIN_COLORS.surfaceMuted,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#323846',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeBadgeText: {
    color: ADMIN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  successBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: ADMIN_COLORS.success,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  successBadgeText: {
    color: '#f5fff8',
    fontSize: 12,
    fontWeight: '800',
  },
  reviewButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#2b0718',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reviewButtonText: {
    color: ADMIN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 58,
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#354053',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    color: ADMIN_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  emptyCopy: {
    marginTop: 8,
    color: ADMIN_COLORS.textMuted,
    fontSize: 14,
    textAlign: 'center',
    maxWidth: 420,
  },
});
